travis:
  secure:
    BINSTAR_TOKEN: US/IB3KoVBR44OClYWTiyX2LFGDFVnM9aGtBtJB2B7e1mcBWhFyTQtMLAXhipO1oqNbHmf/6lOFqT8SgHV5DPPM9cQsS4EiB8wa6W3UijUL431COcRHdGXGvoUhoIpNt4TNDST5X7AyZ4KbKbftN7YTOJqR3EUPa0JGRTOumB7lhv4gbqgYoozGnG3Xc+7W6y7LxaPUuuFpGOGv86GVxd8JUgbEaflwVdScqR32pGu6yCXbHtRplrbJvii3VZe+/+vIRAXq00ZOMDUdMZ6CWhwy4YV+zHIsZduY9en3VkppQ5hNXOinf9BiYEVKNMTBa0MWcmpYKldMSUyReOQdkwmuJAF8us06QUfmhE0fyx+hIdhohToqBWTl288FcM0v4JFBobOA/LTfIICE79ftOItqzMlLE82qkoMYtcoArV9vE7A4hdpJ3xd3yiyctBx1jz4qx3CzdB71ovOMCjDLzD2EKTxc3qqO8nRF+WAQ4CSxVw4smy4VVVcC2bf8WzFFpdisHhya+z3y8WeH0NMHi1UpLSJMriAv+nBwtzHSvhbaVC/hmgtTNwJCITf1R8mjQW0SjJkJ53y7YwVvnLlYzi6Zmmo9yxojr8Hy5G2AJMfTE5d3wDWs9lHRZHXbs6dylvoVEcUB3PXdiW/rmBAJ1oEr6A5IiFDpGpTCAyq8YzpY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
